name: m_and_r_quiz_admin_panel
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  #Session Helper
  shared_preferences: ^2.2.3

  # Network Image
  image_network: ^2.5.6

  #API handler
  toastification:  ^2.0.0

  #Hover Flutter
  hovering: ^1.0.4

  #Scrool Index
  scroll_to_index: ^3.0.1

  #DATE FORMATTER
  intl: ^0.19.0

  ########################################## ROUTING ##########################################
  go_router: ^14.2.1

  ############################# PICKER ########################
  image_picker: ^1.1.2
  file_picker: ^8.0.6


  ################################  ANIMATION  ################################
  flutter_animate: ^4.5.0

  #Url Launcher
  url_launcher: ^6.3.0
  flutter_custom_tabs: ^2.1.0

  ######################################### FIREBASE ########################################
  #Core
  firebase_core: ^3.2.0
  #Firebase Storage
  firebase_storage: ^12.1.1
  #Cloud Firestore
  cloud_firestore: ^5.1.0

  #Responsive Grid
  responsive_grid_list: ^1.4.0

  #Country Code
  country_code_picker: ^3.0.0

  # #CSC Picker
  # csc_picker: ^0.2.7

  

  #HTTPs
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  

flutter:


  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

